// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ebc843bc-2a14-4355-b6e3-2fd950a4fa20",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jwEQyAkOK",
    "aws_user_pools_web_client_id": "614ojm3hc45defggdcfag0q17u"
};


export default awsmobile;
